name: CI Lambda

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: pip install -r requirements.txt bandit pytest-cov

      - name: Tests + Coverage
        run: pytest --cov=src --cov-report=xml

      - name: Security Scan
        run: bandit -r src

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


      - name: Zip Lambda
        run: zip -r lambda.zip src

      - name: Copy Lambda package to Terraform directory
        run: cp lambda.zip terraform/

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.3

      - name: Deploy Terraform
        if: github.ref == 'refs/heads/main'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve
